audit_header: false
title: Hoss Pratt Video Blog
description: If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Hoss Pratt
  license_number:
  about_markdown: >-
    One word describes the man who gets more results out of real estate agents than any other trainer in the country…’Passion.’ After just 3 years in the business as a real estate professional, Hoss Pratt produced over $20 million in sales…which says something about a guy who left his life as a dairy farmer and dove head-first into real estate.
    <br><br>
    A nationally known authority when it comes to lead generation and lead conversion, Hoss has demonstrated and proven time and time again during his stellar 10 year career that using his revolutionary strategies can move real estate agents from stuck to super-charged in just months…changing lives and changing fortunes.
    <br><Br>
    The agents exposed to Hoss’ infectious speaking and coaching style find it hard NOT to succeed. He is a master at converting prospects into clients, fence sitters into sellers. Many agents are getting amazing results using Hoss’ cutting edge lead generation & conversion system.
  market:
  brand: Hoss Pratt International
  brokerage:
  address: 2745 N. Dallas Parkway, Suite 640<br>Plano, TX 75093
  phone: 214-495-0000
  email: hoss@hosspratt.com
  url: http://www.seemywebsite.org/newhosspratt/
  first_CTA_text: Schedule a Free Strategy Session
  first_CTA_URL: http://www.strategicsuccesscall.com
  second_CTA_text:
  second_CTA_URL:
  VR_form:
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/HossPratt
  linkedin_url: https://www.linkedin.com/in/hosspratt
  gplus_url: https://plus.google.com/u/0/115976426032834109775
  youtube_url: https://www.youtube.com/user/hosspratt2000
  twitter_url: https://twitter.com/hosspratt
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title:
  categories: News & Politics
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from --CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Francisco, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:
images:
  client_headshot_path: '/img/headshot.png'
  hero_logo_path: '/img/logo-white.png'
  hero_text:
  hero_background_hex: '#122F5B'
  hero_image_path: '/img/banner.jpg'
  hoss-img: '/img/hoss-img.png'
brand_color: '#FFC400'
theme_color: '#122F5B'
theme_text_color: '#fff'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
